// Code generated by MockGen. DO NOT EDIT.
// Source: assets.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	assets "github.com/openshift-psap/special-resource-operator/pkg/assets"
)

// MockAssets is a mock of Assets interface.
type MockAssets struct {
	ctrl     *gomock.Controller
	recorder *MockAssetsMockRecorder
}

// MockAssetsMockRecorder is the mock recorder for MockAssets.
type MockAssetsMockRecorder struct {
	mock *MockAssets
}

// NewMockAssets creates a new mock instance.
func NewMockAssets(ctrl *gomock.Controller) *MockAssets {
	mock := &MockAssets{ctrl: ctrl}
	mock.recorder = &MockAssetsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAssets) EXPECT() *MockAssetsMockRecorder {
	return m.recorder
}

// GetFrom mocks base method.
func (m *MockAssets) GetFrom(dir string) []assets.Metadata {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFrom", dir)
	ret0, _ := ret[0].([]assets.Metadata)
	return ret0
}

// GetFrom indicates an expected call of GetFrom.
func (mr *MockAssetsMockRecorder) GetFrom(dir interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFrom", reflect.TypeOf((*MockAssets)(nil).GetFrom), dir)
}

// ValidStateName mocks base method.
func (m *MockAssets) ValidStateName(path string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidStateName", path)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ValidStateName indicates an expected call of ValidStateName.
func (mr *MockAssetsMockRecorder) ValidStateName(path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidStateName", reflect.TypeOf((*MockAssets)(nil).ValidStateName), path)
}
